services:
    base:
        &base
        build: .
        image: emerger:base
    dev:
        <<: *base
        working_dir: /work
        volumes:
            - ./:/work
        command: R
        tty: true
        stdin_open: true
    prod:
        <<: *base
        working_dir: /pkg
        command: R
        tty: true
        stdin_open: true
