services:
    dev:
        build: .
        image: rocker/r2u:latest
        working_dir: /work
        volumes:
            - ./:/work
        command: R
        tty: true
        stdin_open: true

    prod:
        build: .
        working_dir: /pkg
        command: R
        tty: true
        stdin_open: true

