services:
    base:
        &base
        build: .
        image: emerger:base

    dev:
        <<: *base
        working_dir: /home/rstudio/work
        environment:
            PASSWORD: "oligonucleotide"
        volumes:
            - ./:/home/rstudio/work
            - rlib:/home/rstudio/R
        command: bash
        restart: unless-stopped

    prod:
        <<: *base
        working_dir: /pkg
        command: bash
        tty: true
        stdin_open: true

volumes:
    rlib:
